<?xml version="1.0" encoding="utf-8"?><Database Name="BAACINS" Class="dbAccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=alldev;Initial Catalog=BAACINS;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BAACINSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="UP.AppMenu" Member="AppMenus">
    <Type Name="AppMenu">
      <Column Name="MenuNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuSeq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuDesc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MenuUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MenuGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.AppMenuAccess" Member="AppMenuAccesses">
    <Type Name="AppMenuAccess">
      <Column Name="MenuNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRole" Type="System.String" DbType="NVarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.FileType" Member="FileTypes">
    <Type Name="FileType">
      <Column Name="FileTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileTypeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.VW_TellerPaymentDetail" Member="VW_TellerPaymentDetails">
    <Type Name="VW_TellerPaymentDetail">
      <Column Name="TellerPaymentDetailID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordType" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="SequenceNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CompanyAccount" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="PaymentTime" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="PaymentDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ref3" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BranchCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="TellerNo" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="KindOfTransaction" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="PaymentBy" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ChequeNo" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ChequeBankCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Filler" Type="System.String" DbType="NVarChar(77)" CanBeNull="true" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="MatchingID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DivisionAreaCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="UpperDivisionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchingDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_REGION" Member="VW_REGIONs">
    <Type Name="VW_REGION">
      <Column Name="REGION_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="REGION_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_PROVINCE" Member="VW_PROVINCEs">
    <Type Name="VW_PROVINCE">
      <Column Name="REGION_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="REGION_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BRANCH" Member="VW_BRANCHes">
    <Type Name="VW_BRANCH">
      <Column Name="REGION_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="REGION_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_NO" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="BRANCH_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BASE_CODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_Title" Member="VW_Titles">
    <Type Name="VW_Title">
      <Column Name="TitleCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_addrAmphur" Member="VW_addrAmphurs">
    <Type Name="VW_addrAmphur">
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_addrProvince" Member="VW_addrProvinces">
    <Type Name="VW_addrProvince">
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_addrTambon" Member="VW_addrTambons">
    <Type Name="VW_addrTambon">
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="DistrictCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.StatusDetail" Member="StatusDetails">
    <Type Name="StatusDetail">
      <Column Name="StatusCode" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatusName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.UploadFileDetail" Member="UploadFileDetails">
    <Type Name="UploadFileDetail">
      <Column Name="FileID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TellerPaymentDetailID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileOriginName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadBy" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="EncryptCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteBy" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.UnmatchCause" Member="UnmatchCauses">
    <Type Name="UnmatchCause">
      <Column Name="CauseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CauseDescription" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="isUpdateUnmatched" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isCompCode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isAmount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRef1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRef2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRefName" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isPaymentdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRefund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isUploadFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isSpin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isGL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="UP.UnmatchPayment" Member="tbUnmatchPayments">
    <Type Name="tbUnmatchPayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CauseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TellerPaymentDetailID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="RefName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DepNo" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApproveBy" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="BranchCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReturnTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UP.ReturnType" Member="ReturnTypes">
    <Type Name="ReturnType">
      <Column Name="ReturnTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReturnTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="UP.EMPLOYEE_SELECT" Method="EMPLOYEE_SELECT">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.String" DbType="NVarChar(7)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="EMPLOYEE_SELECTResult">
      <Column Name="USER_ID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="USER_NAME" Type="System.String" DbType="NVarChar(251)" CanBeNull="true" />
      <Column Name="POSITIONNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ROLECODE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ROLENAME" Type="System.String" DbType="NVarChar(521)" CanBeNull="true" />
      <Column Name="BRANCH_NO" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BRANCH_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="REGION_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="REGION_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PROVINCE_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="isBranch" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GETUSERBYHQ_SELECT" Method="GETUSERBYHQ_SELECT">
    <Parameter Name="BRANCH_NO" Parameter="bRANCH_NO" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="GETUSERBYHQ_SELECTResult">
      <Column Name="USERID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="USERFULLNAME" Type="System.String" DbType="NVarChar(251)" CanBeNull="true" />
      <Column Name="HRCODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_NO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SPUP_APPMENU_SELECTFORMASTERPAGE" Method="SPUP_APPMENU_SELECTFORMASTERPAGE">
    <Parameter Name="ROLE_CODE" Parameter="rOLE_CODE" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="SPUP_APPMENU_SELECTFORMASTERPAGEResult">
      <Column Name="MENUNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MENUSEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MENUDESC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MENUURL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MENUGROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>